name: Write and publish on LinkedIn

on:
  push:
    branches: release

jobs:
  write:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4.1.7
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - uses: agentic-actions/task-orchestrator@v1
      agentic: true
      with:
        prompt: Coordinate the a team of agents to draft a release note for LinkedIn based on recent activities in the repo
        sub-agents:
        - uses: agentic-actions/content-writer@v1
          prompt: Write for LinkedIn short post for dev audience. Causal tone.
        - uses: agentic-actions/code-analyzer@v2.1.x
          prompt: Summarize recent activities in the code base
        - uses: microsoft/legal-reviewer@v1
          prompt: Identity and address potential legal issues in the content

    - name: upload artifact build-results
      uses: actions/upload-artifact@v4
      with:
        name: linkedin-draft
        path: linkedin-draft
      timeout-minutes: 5
    
  publish:
    environment: production
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4.1.7
      timeout-minutes: 2

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - uses: actions/download-artifact@v4
      with:
        name: linkedin-draft
        path: linkedin-draft

    - run: npx codecov
